// This file was auto-generated by ML.NET Model Builder. 

using System;
using FirstTryAtML101ML.Model;

namespace FirstTryAtML101ML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Col1 = 13868.85F,
                Col2 = 11063.38F,
                Col3 = 5452.781F,
                Col4 = 3019.123F,
                Col5 = 2338.009F,
                Col6 = 894.0856F,
                Col7 = 479.2575F,
                Col8 = 358.4319F,
                Col9 = 283.7598F,
                Col10 = 253.8049F,
                Col11 = 256.5529F,
                Col12 = 257.3511F,
                Col13 = 268.1667F,
                Col14 = 288.2473F,
                Col15 = 289.4342F,
                Col16 = 0F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Col0 with predicted Col0 from sample data...\n\n");
            Console.WriteLine($"Col1: {sampleData.Col1}");
            Console.WriteLine($"Col2: {sampleData.Col2}");
            Console.WriteLine($"Col3: {sampleData.Col3}");
            Console.WriteLine($"Col4: {sampleData.Col4}");
            Console.WriteLine($"Col5: {sampleData.Col5}");
            Console.WriteLine($"Col6: {sampleData.Col6}");
            Console.WriteLine($"Col7: {sampleData.Col7}");
            Console.WriteLine($"Col8: {sampleData.Col8}");
            Console.WriteLine($"Col9: {sampleData.Col9}");
            Console.WriteLine($"Col10: {sampleData.Col10}");
            Console.WriteLine($"Col11: {sampleData.Col11}");
            Console.WriteLine($"Col12: {sampleData.Col12}");
            Console.WriteLine($"Col13: {sampleData.Col13}");
            Console.WriteLine($"Col14: {sampleData.Col14}");
            Console.WriteLine($"Col15: {sampleData.Col15}");
            Console.WriteLine($"Col16: {sampleData.Col16}");
            Console.WriteLine($"\n\nPredicted Col0 value {predictionResult.Prediction} \nPredicted Col0 scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
